0 add ao-volume 2
9 add ao-volume -2 
m cycle ao-mute
\ cycle audio-pitch-correction
| cycle play-direction
WHEEL_UP      seek 10
WHEEL_DOWN    seek -10
WHEEL_LEFT    add ao-volume -2
WHEEL_RIGHT   add ao-volume 2
#F5 set playlist-pos ${playlist-pos}
F5 playlist-play-index current
#; video-reload "${vid}"
h playlist-shuffle; show-text playlist-shuffle
H set playlist-pos 0
ctrl+c run /bin/sh -c "printf %s '${path}' | xclip -i -sel c"
ctrl+d run dragon -x "${path}"
#ctrl+v
#ctrl+C run sh -c "printf '%s' '${=playlist}' | jq -r '.[].filename' | xclip -i -sel c"
#ctrl+D run sh -c "printf '%s' '${=playlist}' | jq -r '.[].filename' | xargs -d \\\\n -n 100 -P 3 dragon -x -a"
#ctrl+V
K cycle-values keep-open yes no
ctrl+Q cycle save-position-on-quit
bs cycle-values speed 1 4/1.1
#  show-text "${playlist}"
k script-binding toggle_crop
